name: ♻️ Update GitHub Streak Image

on:
  schedule:
    - cron: '0 */12 * * *'  # runs every 12 hours
  workflow_dispatch:        # allows manual trigger

permissions:
  contents: write

jobs:
  update-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate streak image
        run: |
          mkdir -p assets
          curl -o assets/github-streak.png "https://github-readme-streak-stats.herokuapp.com/?user=Pranay22077&theme=default&hide_border=true&background=FFFFFF00&ring=FF8C00&fire=FFB300&currStreakLabel=FF7B00"


      - name: Commit and push updated streak image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/github-streak.png
          git commit -m "Auto-update GitHub Streak image [skip ci]" || echo "No changes to commit"
          git push
